# Generated by Django 5.0.7 on 2024-07-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='titulo',
        ),
    ]
