# Generated by Django 5.0.7 on 2024-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_receta_descripcion_remove_receta_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(default='Descripcion por defecto', max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='receta',
            name='titulo',
            field=models.CharField(default='Titulo por defecto', max_length=100, verbose_name='Titulo'),
        ),
    ]
